# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXmu
PORTVERSION=	1.1.3
PORTEPOCH=	1
CATEGORIES=	x11-toolkits

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Miscellaneous Utilities libraries

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		lib32 xorg xorg-cat:lib
USE_LDCONFIG=	yes
USE_XORG=	xorgproto x11 xt xext

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
