# $FreeBSD$

USE_LIB32=	yes
MASTERDIR=	${.CURDIR}/../mesa-dri

.include "${MASTERDIR}/Makefile"

CONFIGURE_ARGS+=--disable-asm # ?

DESCR=		${MASTERDIR}/pkg-descr
PLIST=		${MASTERDIR}/pkg-plist
PKGHELP=	${MASTERDIR}/pkg-help
PKGINSTALL=	${MASTERDIR}/pkg-install
PKGDEINSTALL=	${MASTERDIR}/pkg-deinstall
