# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXxf86vm
PORTVERSION=	1.1.4
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Vidmode Extension

LICENSE=	MIT

USES=		lib32 cpe xorg xorg-cat:lib
USE_LDCONFIG=	yes
USE_XORG=	xorgproto x11 xext

CPE_PRODUCT=	libxxf86vm
CPE_VENDOR=	x

.include <bsd.port.mk>
