# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXinerama
PORTVERSION=	1.1.4
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 Xinerama library

LICENSE=	MIT

USES=		cpe lib32 xorg xorg-cat:lib
USE_LDCONFIG=	yes
USE_XORG=	x11 xext xorgproto

CPE_PRODUCT=	libxinerama
CPE_VENDOR=	x

.include <bsd.port.mk>
