# $FreeBSD$

# mesa-libs itself is a slave port of mesa-dri

USE_LIB32=	yes
MESADIR= 	${.CURDIR}/../mesa-libs

.include "${.CURDIR}/../mesa-libs/Makefile"

DESCR=		${MESADIR}/pkg-descr
PLIST=		${MESADIR}/pkg-plist
PKGHELP=	${MESADIR}/pkg-help
PKGINSTALL=	${MESADIR}/pkg-install
PKGDEINSTALL=	${MESADIR}/pkg-deinstall
