# $FreeBSD$

USE_LIB32=	yes
MASTERDIR=	${.CURDIR}/../libjpeg-turbo

.include "${MASTERDIR}/Makefile"

BUILD_DEPENDS:=	${BUILD_DEPENDS:C|graphics/jpeg-turbo|graphics/libjpeg-turbo|}
RUN_DEPENDS:=	${RUN_DEPENDS:C|graphics/jpeg-turbo|graphics/libjpeg-turbo|}
