# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXdamage
PORTVERSION=	1.1.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Damage extension library

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		lib32 xorg xorg-cat:lib
USE_LDCONFIG=	yes
USE_XORG=	x11 xfixes xorgproto

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
