# $FreeBSD$

USE_LIB32=	yes
MASTERDIR=	${.CURDIR}/../virtualgl

.include "${MASTERDIR}/Makefile"

LIB32_PATTERN:=	(^VirtualGL\/bin\/\.vglrun\.vars32|^VirtualGL\/lib32|^VirtualGL\/fakelib32|${LIB32_PATTERN})
