# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libXrender
PORTVERSION=	0.9.10
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Render extension library

LICENSE=	MIT

USES=		lib32 xorg xorg-cat:lib
USE_LDCONFIG= yes
USE_XORG=	x11 xorgproto

.include <bsd.port.mk>
